augment:
  data:
    args:
      dataset: 'CIFAR10'
      train_root: './data'
      valid_root: './data'
      cutout: 16
      jitter: True
  data_loader:
    args:
      valid_ratio: 0
      trn_batch_size: 96
      val_batch_size: 96
  estimator:
    train:
      type: 'Default'
      w_optim:
        type: 'sgd'
        args:
          lr: 0.025
          momentum: 0.9
          weight_decay: 0.0003
          nesterov: True
      lr_scheduler:
        type: 'cosine'
        args:
          eta_min: 0.0
      aux_weight: 0.4
      drop_path_prob: 0.2
      w_grad_clip: 5.
      epochs: 600
      print_freq: 200
      save_freq: 200
ops:
  ops_order: 'act_weight_bn'
  affine: True
criterion:
  type: 'LS'
  eta: 0.1
model:
  type: 'DARTS'
  args:
    n_classes: 10             # use 10 for MNIST, CIFAR10
    chn_in: 3           # 3 for ImageNet/CIFAR10, 1 for MNIST
    chn: 36        # init channel
    channel_multiplier: 3   # init channel multiplier
    nodes: 4                # num of nodes (states) per layer
    layers: 20              # num of DAG layers (cells) in model
    shared_a: True
    auxiliary: True
log:
  writer: False
device:
  gpus: 'all'
  seed: 2
genotypes:
  gt_str: ''
  gt_path: ''
init:
  type: 'he_normal_fout'