search:
  data:
    args:
      dataset: 'CIFAR10'
      train_root: './data'
      valid_root: './data'
  data_loader:
    args:
      valid_ratio: 0.15
      trn_batch_size: 64
      val_batch_size: 64
  estimator:
    search:
      type: 'SuperNet'
      w_optim:
        type: 'sgd'
        args:
          lr: 0.025
          momentum: 0.9
          weight_decay: 0.0003
          nesterov: True
      lr_scheduler:
        type: 'cosine'
        args:
          eta_min: 0.001
      w_grad_clip: 5.
      epochs: 50
optim:
  type: 'WeightedSum'
  args:
    w_momentum: 0.9
    w_weight_decay: 0.0003
    a_optim:
      type: 'adam'
      args:
        lr: 0.0003
        betas: [0.5, 0.999]
        weight_decay: 0.001
mixed_op:
  type: 'WeightedSum'
  primitives: ['AVG', 'MAX', 'SC3', 'SC5', 'DC3', 'DC5', 'IDT', 'NIL']
ops:
  ops_order: 'act_weight_bn'
  affine: False
model:
  type: 'DARTS'
  args:
    n_classes: 10             # use 10 for MNIST, CIFAR10
    chn_in: 3           # 3 for ImageNet/CIFAR10, 1 for MNIST
    chn: 16        # init channel
    channel_multiplier: 3   # init channel multiplier
    nodes: 4                # num of nodes (states) per layer
    layers: 8               # num of DAG layers (cells) in model
    shared_a: True
    auxiliary: False