hpspace:
  hp_path: 
  hp_dict:
    mixed_op.primitives: [['SC3','SC5','NC3','NC5'], ['DC3','DC5','NC3','NC5'], ['SC3','SC5','DC3','DC5']]
    # search.data.dloader.valid_ratio: [0.5, 0.8, 0.9]
    # search.estimator.search.warmup_epochs: [0, 20, 40, 60]
    # search.estimator.search.epochs: [25, 50, 100, 200]
    # search.estimator.search.w_optim.args.lr: [0.035, 0.01, 0.1]
optim:
  type: 'Random'
log:
  writer: False
device:
  gpus: 'all'
  seed: 2
hptune:
  estimator:
    tune:
      type: 'HPTune'
      batch_size: 1
      epochs: 10
      trial_args:
        proc: 'search'
        name: 'trial'
        chkpt:
        device: 'all'
        exp: 'exp'
      trial_config:
        search:
          data:
            args:
              dataset: 'CIFAR10'
              train_root: './data'
              valid_root: './data'
          data_loader:
            args:
              valid_ratio: 0.2
              trn_batch_size: 64
              val_batch_size: 64
              workers: 0
          estimator:
            search:
              type: 'SubNet'
              w_optim:
                type: 'sgd'
                args:
                  lr: 0.035
                  momentum: 0.9
                  nesterov: True
                  weight_decay: 0.0001
              lr_scheduler:
                type: 'cosine'
                args:
                  eta_min: 0.001
              subnet_epochs: 2
              epochs: 1
        augment:
          data:
            args:
              dataset: 'CIFAR10'
              train_root: './data'
              valid_root: './data'
          data_loader:
            args:
              valid_ratio: 0
              trn_batch_size: 64
              val_batch_size: 64
          estimator:
            train:
              type: 'Default'
              epochs: 250
              w_optim:
                type: 'sgd'
                args:
                  lr: 0.1
                  momentum: 0.9
                  weight_decay: 0.0005
                  nesterov: False
              lr_scheduler:
                type: 'cosine'
                args:
                  eta_min: 0.0
        optim:
          type: 'Random'
        mixed_op:
          type: 'Index'
        ops:
          ops_order: 'weight_bn'
          affine: False
        criterion:
          type: 'LS'
          eta: 0.1
        model:
          type: 'CIFAR-ResNet-10'
          args:
            n_classes: 10             # use 10 for MNIST, CIFAR10
            chn_in: 3   
            chn: 16
        log:
          writer: False
        device:
          gpus: 'all'
          seed: 2
        genotypes:
          gt_str: ''
          gt_path: ''