search:
  estimator:
    nasbench:
      type: 'NASBench'
      epochs: 200
      save_freq: 0
      record_path: './data/nasbench101/nasbench_full.tfrecord'
      arch_update_epoch_start: 0
      arch_update_epoch_intv: 1
      arch_update_batch: 2048
optim:
  type: 'Random'
log:
  writer: False
device:
  gpus: 'all'
  seed: 2
genotypes:
  gt_str: ''
  gt_path: ''