imports:
  - 'combo_nas.contrib.estimator.nasbench'
search:
  estimator:
    nasbench:
      type: 'NASBench'
      epochs: 5000
      save_gt: False
      record_path: './data/nasbench101/nasbench_only108.tfrecord'
      arch_update_epoch_start: 1
      arch_update_epoch_intv: 1
      arch_update_batch: 1
optim:
  type: 'Random'
model:
  type: 'NASBench'