search:
  data:
    type: 'CIFAR10'
    # type: 'MNIST'
    # type: 'ImageNet'
    train_root: './data'
    valid_root: './data'
    dloader:
      type: 'pytorch'
      split_ratio: 0.8
      trn_batch_size: 64
      val_batch_size: 64
      workers: 2
      cutout: 0
      jitter: False
  estimator:
    warmup:
      type: 'Default'
      w_optim:
        type: 'sgd'
        args:
          lr: 0.1
          momentum: 0.9
          nesterov: True
          weight_decay: 0.0001
      lr_scheduler:
        type: 'cosine'
        args:
          eta_min: 0.001
      w_grad_clip: 0.0
      drop_path_prob: 0.0
      epochs: 50
      print_freq: 200
      save_freq: 0
      aux_weight: 0.0
    supernet:
      type: 'SuperNet'
      w_optim:
        type: 'sgd'
        args:
          lr: 0.035
          momentum: 0.9
          nesterov: True
          weight_decay: 0.0001
      lr_scheduler:
        type: 'cosine'
        args:
          eta_min: 0.0
      metrics:
        type: 'AddAggMetrics'
        # type: 'MultAggMetrics'
        args:
          target_val: 40000000
          lamd: 0.05
          # alpha: 1.0
          # beta: 0.05
          metrics: 'RASPTraversalMetrics'
          args:
            input_shape: [1, 3, 32, 32]
            metrics: 'RASPFLOPSMetrics'
      w_grad_clip: 0.0
      drop_path_prob: 0.0
      epochs: 200
      print_freq: 200
      save_freq: 0
      arch_update_epoch_start: 0
      arch_update_epoch_intv: 1
      arch_update_intv: -1
      arch_update_batch: 1
      plot: False
      aux_weight: 0.0
augment:
  data:
    type: 'CIFAR10'
    # type: 'MNIST'
    # type: 'ImageNet'
    train_root: './data'
    valid_root: './data'
    dloader:
      type: 'pytorch'
      split_ratio: 0
      trn_batch_size: 64
      val_batch_size: 64
      workers: 2
      cutout: 0
      jitter: False
  estimator:
    train:
      type: 'Default'
      epochs: 250
      w_optim:
        type: 'sgd'
        args:
          lr: 0.1
          momentum: 0.9
          weight_decay: 0.0005
          nesterov: False
      lr_scheduler:
        type: 'cosine'
        args:
          eta_min: 0.0
      aux_weight: 0.0
      drop_path_prob: 0.0
      w_grad_clip: 0.0
      print_freq: 200
      save_freq: 0
optim:
  type: 'BinGate'
  args:
    n_samples: 2
    renorm: True
    a_optim:
      type: 'adam'
      args:
        lr: 0.006
        betas: [0.0, 0.999]
        weight_decay: 0.0
mixed_op:
  type: 'BinGate'
  primitives:
    - 'IDT'
    - 'SC3'
    - 'SC5'
    - 'SC7'
    - 'NC3'
    - 'NC5'
    - 'NC7'
    - 'DC3'
    # - 'DC5'
ops:
  ops_order: 'weight_bn'
  affine: False
criterion:
  type: 'CE'
model:
  type: 'CIFAR-ResNet-10'
  args:
    n_classes: 10             # use 10 for MNIST, CIFAR10
    chn_in: 3           # 3 for ImageNet/CIFAR10, 1 for MNIST
    chn: 16        # init channel
log:
  writer: False
device:
  gpus: 'all'
  seed: 2
genotypes:
  gt_str: ''
  gt_path: ''
init:
  type: 'he_normal_fout'