search:
  data:
    type: 'CIFAR10'
    # type: 'MNIST'
    # type: 'ImageNet'
    train_root: './data'
    valid_root: './data'
    dloader:
      type: 'pytorch'
      split_ratio: 0.8
      trn_batch_size: 64
      val_batch_size: 64
      workers: 0
      cutout: 0
      jitter: True
  w_optim:
    type: 'sgd'
    lr: 0.035
    lr_min: 0.0
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0001
    # type: 'adabound'
    # lr: 0.001
    # final_lr: 0.05
  a_optim:
    type: 'adam'
    lr: 0.006
    betas: 
      - 0.0
      - 0.999
    weight_decay: 0
  lr_scheduler:
    type: 'cosine'
  w_grad_clip: 0.0
  drop_path_prob: 0.0
  warmup_epochs: 30
  epochs: 200
  print_freq: 200
  save_freq: 0
  plot_path: './searchs'
  gt_file: './searchs'
---
augment:
  data:
    type: 'CIFAR10'
    # type: 'MNIST'
    # type: 'ImageNet'
    train_root: './data'
    valid_root: './data'
    dloader:
      type: 'pytorch'
      split_ratio: 0
      trn_batch_size: 64
      val_batch_size: 64
      workers: 0
      cutout: 16
      jitter: True
  epochs: 600
  genotype: ''
  gt_file: ''
  w_optim:
    type: 'sgd'
    lr: 0.1
    lr_min: 0.0
    momentum: 0.9
    weight_decay: 0.0001
    nesterov: True
  lr_scheduler:
    type: 'cosine'
  drop_path_prob: 0.0
  w_grad_clip: 0.0
  print_freq: 200
  save_freq: 0
---
arch_optim:
  # type: 'DARTS'
  type: 'BinGate'
  # type: 'REINFORCE'
  n_samples: 0
  batch_size: 10
  w_momentum: 0.9
  w_weight_decay: 0.0003
  renorm: True
---
mixed_op:
  type: 'BinGate'
  # type: 'DARTS'
---
ops:
  sepconv_stack: True
  ops_order: 'weight'
  affine: False
---
criterion:
  type: 'LS'
  eta: 0.1
---
model:
  type: 'ResNet-50'
  classes: 10             # use 10 for MNIST, CIFAR10
  channel_in: 3   
  channel_init: 64
---
primitives:
  - 'SC3'
  - 'SC5'
  - 'SC7'
  - 'NC3'
  - 'NC5'
  - 'NC7'
  - 'DC3'
  - 'DC5'
  - 'C11'
---
log:
  writer: False
---
device:
  gpus: 'all'
  seed: 2
---
tune:
  tuner: 'Random'
