imports:
  - 'combo_nas.contrib.metrics.profiler_metrics'
search:
  data:
    args:
      dataset: 'CIFAR10'
      train_root: './data'
      valid_root: './data'
  data_loader:
    args:
      valid_ratio: 0.2
      trn_batch_size: 64
      val_batch_size: 64
      workers: 0
  estimator:
    supernet:
      type: 'SuperNet'
      w_optim:
        type: 'sgd'
        args:
          lr: 0.035
          momentum: 0.9
          nesterov: True
          weight_decay: 0.0001
      lr_scheduler:
        type: 'cosine'
        args:
          eta_min: 0.0
      criterion:
        - type: 'CE'
        - type: 'AddMetrics'
          mode: 'valid'
          args:
            target_val: 4.2
            lamd: 0.05
            metrics: 'lat'
      metrics:
        lat:
          type: 'RASPTraversalMetrics'
          args:
            input_shape: [1, 3, 224, 224]
            metrics: 'LocalProfilerMetrics'
            args:
              head: ['type', 'prim_type', 'in_shape', 'out_shape']
              device: 'cuda'
      epochs: 200
optim:
  type: 'BinGate'
  args:
    n_samples: 2
    renorm: True
    a_optim:
      type: 'adam'
      args:
        lr: 0.006
        betas: [0.0, 0.999]
        weight_decay: 0.0
mixed_op:
  type: 'BinGate'
  primitives:
    - 'SC3'
    - 'SC5'
    - 'SC7'
    - 'NC3'
    - 'NC5'
    - 'NC7'
    - 'DC3'
    # - 'DC5'
ops:
  ops_order: 'weight_bn'
  affine: False
model:
  type: 'CIFAR-ResNet-10'
  args:
    n_classes: 10             # use 10 for MNIST, CIFAR10
    chn_in: 3           # 3 for ImageNet/CIFAR10, 1 for MNIST
    chn: 16        # init channel
