search:
  data:
    args:
      dataset: 'CIFAR10'
      train_root: './data'
      valid_root: './data'
  data_loader:
    args:
      valid_ratio: 0.2
      trn_batch_size: 64
      val_batch_size: 64
  estimator:
    search:
      type: 'SubNet'
      w_optim:
        type: 'sgd'
        args:
          lr: 0.035
          momentum: 0.9
          nesterov: True
          weight_decay: 0.0001
      lr_scheduler:
        type: 'cosine'
        args:
          eta_min: 0.001
      subnet_epochs: 50
      epochs: 200
augment:
  data:
    args:
      dataset: 'CIFAR10'
      train_root: './data'
      valid_root: './data'
  data_loader:
    args:
      valid_ratio: 0
      trn_batch_size: 64
      val_batch_size: 64
  estimator:
    train:
      type: 'Default'
      epochs: 250
      w_optim:
        type: 'sgd'
        args:
          lr: 0.1
          momentum: 0.9
          weight_decay: 0.0005
          nesterov: False
      lr_scheduler:
        type: 'cosine'
        args:
          eta_min: 0.0
      aux_weight: 0.0
      w_grad_clip: 0.0
      print_freq: 200
      save_freq: 0
optim:
  type: 'Random'
mixed_op:
  type: 'Index'
  primitives:
    - 'SC3'
    - 'SC5'
    - 'SC7'
    - 'NC3'
    - 'NC5'
    - 'NC7'
    - 'DC3'
    - 'DC5'
ops:
  ops_order: 'weight_bn'
  affine: False
criterion:
  type: 'LS'
  eta: 0.1
model:
  type: 'CIFAR-ResNet-10'
  args:
    n_classes: 10             # use 10 for MNIST, CIFAR10
    chn_in: 3   
    chn: 16
log:
  writer: False
device:
  gpus: 'all'
  seed: 2
genotypes:
  gt_str: ''
  gt_path: ''
